/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MypageImport } from './routes/mypage'
import { Route as DonercardImport } from './routes/donercard'
import { Route as DonateImport } from './routes/donate'
import { Route as ChatImport } from './routes/chat'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const MypageRoute = MypageImport.update({
  id: '/mypage',
  path: '/mypage',
  getParentRoute: () => rootRoute,
} as any)

const DonercardRoute = DonercardImport.update({
  id: '/donercard',
  path: '/donercard',
  getParentRoute: () => rootRoute,
} as any)

const DonateRoute = DonateImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRoute,
} as any)

const ChatRoute = ChatImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatImport
      parentRoute: typeof rootRoute
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateImport
      parentRoute: typeof rootRoute
    }
    '/donercard': {
      id: '/donercard'
      path: '/donercard'
      fullPath: '/donercard'
      preLoaderRoute: typeof DonercardImport
      parentRoute: typeof rootRoute
    }
    '/mypage': {
      id: '/mypage'
      path: '/mypage'
      fullPath: '/mypage'
      preLoaderRoute: typeof MypageImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/donate': typeof DonateRoute
  '/donercard': typeof DonercardRoute
  '/mypage': typeof MypageRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/donate': typeof DonateRoute
  '/donercard': typeof DonercardRoute
  '/mypage': typeof MypageRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/donate': typeof DonateRoute
  '/donercard': typeof DonercardRoute
  '/mypage': typeof MypageRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/chat' | '/donate' | '/donercard' | '/mypage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/chat' | '/donate' | '/donercard' | '/mypage'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/chat'
    | '/donate'
    | '/donercard'
    | '/mypage'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChatRoute: typeof ChatRoute
  DonateRoute: typeof DonateRoute
  DonercardRoute: typeof DonercardRoute
  MypageRoute: typeof MypageRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChatRoute: ChatRoute,
  DonateRoute: DonateRoute,
  DonercardRoute: DonercardRoute,
  MypageRoute: MypageRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/chat",
        "/donate",
        "/donercard",
        "/mypage"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/chat": {
      "filePath": "chat.tsx"
    },
    "/donate": {
      "filePath": "donate.tsx"
    },
    "/donercard": {
      "filePath": "donercard.tsx"
    },
    "/mypage": {
      "filePath": "mypage.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
